name 'volgactf-qualifier'
maintainer 'Alexander Pyatkin'
maintainer_email 'aspyatkin@gmail.com'
license 'MIT'
description 'Installs and configures VolgaCTF Qualifier platform'
version '2.2.1'

depends 'nodejs', '~> 7.0'
depends 'ngx', '~> 2.2'
depends 'agit', '~> 0.1'
depends 'tls', '~> 4.1'
