name 'volgactf-qualifier'
maintainer 'Aleksandr Piatkin'
maintainer_email 'oss@aptkn.ch'
license 'MIT'
description 'Installs and configures VolgaCTF Qualifier platform'
version '2.3.0'

depends 'nodejs', '~> 7.0'
depends 'ngx', '~> 2.2'
depends 'agit', '~> 0.1'
depends 'tls', '~> 4.1'
