name 'volgactf-qualifier'
maintainer 'Alexander Pyatkin'
maintainer_email 'aspyatkin@gmail.com'
license 'MIT'
description 'Installs and configures VolgaCTF Qualifier platform'
version '2.0.2'

depends 'nodejs', '~> 6.0.0'
depends 'ngx'
depends 'agit', '~> 0.1.2'
depends 'tls', '~> 3.2.0'
depends 'instance', '~> 2.0.1'
